### ISSUE TITLE
SSL required for GetUserMedia()

### ISSUE THREAD

**Issue by Stew-rt** [miguelgrinberg/flask-twilio-video#1]
Hey Miguel,
This is very cool, but I just wanted to note here, I had to add `ssl_context='adhoc'` to app.run() to get this to work from a remote machine as GetUserMedia() seems to be (quite sensibly) blocked in all browsers without SSL ...

**Comment by miguelgrinberg** [comment]
Okay, good to know. I managed to avoid that problem because I use `ngrok` to create a public https URL for it.

**Comment by miguelgrinberg** [comment]
I added a note in the readme file regarding the requirement to use https.
