### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Adal01672** [miguelgrinberg/flask-twilio-video#15]
Hi Miguel,
I have an issue while I click on the connect button

**_error_**
**_it says :_** `127.0.0.1 - - [28/Jun/2021 17:29:14] "[37mPOST /login HTTP/1.1[0m" 200 -` in the console 
**_and the chrome tab_** : 
![image](https://user-images.githubusercontent.com/67435704/123630708-a3552800-d837-11eb-87f3-afb082abbf9a.png)

I hope you can fix it for me.
Thank, you

**Comment by miguelgrinberg** [comment]
This does not provide any information that I can use to help you. Look at the logs in the browser console and in your server.

**Comment by Adal01672** [comment]
import os
from dotenv import load_dotenv
from flask import Flask, render_template, request, abort
from twilio.jwt.access_token import AccessToken
from twilio.jwt.access_token.grants import VideoGrant, ChatGrant
from twilio.rest import Client
from twilio.base.exceptions import TwilioRestException




twilio_account_sid = 'my account sid'
twilio_api_key_sid = 'my api key sid'
twilio_api_key_secret = 'MY API key secret'

twilio_client = Client(twilio_api_key_sid, twilio_api_key_secret,
                       twilio_account_sid)

app = Flask(__name__)


def get_chatroom(name):
    for conversation in twilio_client.conversations.conversations.stream():
        if conversation.friendly_name == name:
            return conversation

    # a conversation with the given name does not exist ==> create a new one
    return twilio_client.conversations.conversations.create(
        friendly_name=name)


@app.route('/')
def index():
    return render_template('index.html')


@app.route('/login', methods=['POST'])
def login():
    username = request.get_json(force=True).get('username')
    if not username:
        abort(401)

    conversation = get_chatroom('My Room')
    try:
        conversation.participants.create(identity=username)
    except TwilioRestException as exc:
        # do not error if the user is already in the conversation
        if exc.status != 409:
            raise

    token = AccessToken(twilio_account_sid, twilio_api_key_sid,
                        twilio_api_key_secret, identity=username)
    token.add_grant(VideoGrant(room='My Room'))
    token.add_grant(ChatGrant(service_sid=conversation.chat_service_sid))

    return {'token': token.to_jwt().decode(),
            'conversation_sid': conversation.sid}


if __name__ == '__main__':
    app.run(host='localhost')

**Comment by Adal01672** [comment]
> This does not provide any information that I can use to help you. Look at the logs in the browser console and in your server.

ok 
`Failed to load resource: the server responded with a status of 403 ()
twilio-video.min.js:51 2021-06-28 11:48:44.382Z | WARN in [NTSIceServerSource #1]: Failed to get ICE servers (using defaults): TwilioError: Invalid Access Token issuer/subject
    at AccessTokenIssuerInvalidError.TwilioError (twilio-video.min.js:53)
    at new AccessTokenIssuerInvalidError (twilio-video.min.js:52)
    at createTwilioError (twilio-video.min.js:52)
    at twilio-video.min.js:38
log @ twilio-video.min.js:51
app.js:76 TwilioError: Invalid Access Token issuer/subject
    at AccessTokenIssuerInvalidError.TwilioError (twilio-video.min.js:53)
    at new AccessTokenIssuerInvalidError (twilio-video.min.js:52)
    at createTwilioError (twilio-video.min.js:52)
    at TwilioConnection.handleMessage (twilio-video.min.js:47)
    at TwilioConnection.EventEmitter.emit (twilio-video.min.js:55)
    at TwilioConnection._handleMessage (twilio-video.min.js:50)
    at WebSocket.<anonymous> (twilio-video.min.js:50)
twilio-video.min.js:51 2021-06-28 11:48:59.888Z | WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Closed: 1006 - `

**Comment by miguelgrinberg** [comment]
Are you sure your twilio credentials are correct?
