### ISSUE TITLE
error with twilio-min-js

### ISSUE THREAD

**Issue by Asfetaw** [miguelgrinberg/flask-twilio-video#17]
Hi 

i wanted to share you this print screen . i get problem launching the app as it is stated . when i inspect the error is located at 'twilio-min-js' which unable to load the video . could you please help if i miss something to include here .
![image](https://user-images.githubusercontent.com/42384777/131226790-03aa37b7-854a-4a6e-b308-f39b1cd00f45.png)

thanks

**Comment by miguelgrinberg** [comment]
You have to use SSL. Chrome does not allow apps to access media services when the connection is not encrypted.

**Comment by Asfetaw** [comment]
Hi Migual;

thank you for your response. The error is happing even when i try to run the app locally( localhost:5000). is this error also associated  to  SSL ? if so, what is your suggestion ? should i need to buy SSL certificate to run the app?

**Comment by miguelgrinberg** [comment]
I recorded a video showing how to do this. Have you seen it? https://www.youtube.com/watch?v=5hdrW6yEwro

You can use ngrok to provision a temporary https URL to your application.

**Comment by Asfetaw** [comment]
yes i used ngrok . i got the temporary url . but receiving the same error

**Comment by miguelgrinberg** [comment]
I'm not really sure how to help. You can see how I do it in the video. If that does not work for you, then maybe try a different browser. You need to figure out why your browser does not provide access to the media APIs, this is all in the browser, it is not a problem with the application or the Twilio library.

**Comment by Asfetaw** [comment]
![image](https://user-images.githubusercontent.com/42384777/131411954-05074cdb-9753-4b91-9d0d-76273bfa4c99.png)
As i showed you , the error is indicated at ' twilio-video.min.js '.  is this showing helping you to understand ? what do you think , am i supposed to do something here ?  because i have tested on chrome and safari but it is showing the same error .

**Comment by miguelgrinberg** [comment]
The error is in the Twilio library because this is where the call to request access to the camera is made. You can see this in the stack trace. It's right there in your screenshot.

I mentioned a several times already that you need to use an https URL. This is also mentioned in the video that I shared. Yet, you are using an http URL. How do you expect this will work without encryption? It is required, nothing I or Twilio can do about that.

**Comment by Asfetaw** [comment]
thank you muguel for your response. i understand what you have said. i might tested on http but i will check that on https  which is generated by ngrok

**Comment by Asfetaw** [comment]
Hi Migual;

i tested via https. it works . it was my problem  i was only using  the http  not https link. once i get the https forwarding  link from ngrok,  able to open the app on chrome and safari. i am closing this requested as solved.

thank you for your swift response .
