### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node'

### ISSUE THREAD

**Issue by sekeyrw** [miguelgrinberg/flask-twilio-video#21]
``` javascript
function addLocalVideo() {
    Twilio.Video.createLocalVideoTrack().then(track => {
        let video = document.getElementById('local').firstChild;
        let trackElement = track.attach();
        trackElement.addEventListener('click', () => { zoomTrack(trackElement); });
        video.appendChild(trackElement);
    });
};
```

I have this error in my console and my video arent showing.
the error points to video.appendChild(trackElement);
I removed ".firstChild" on "let video" and theres no more error but the design is not good anymore
How can I fix this error?

**Comment by miguelgrinberg** [comment]
The `local` div should be defined as follows:

```html
<div id="local" class="participant"><div></div><div class="label">Me</div></div>
```

Note that there is an empty `<div>` element as a first child. Do you have that in your version?

**Comment by sekeyrw** [comment]
```javascript
      <div id="local" class="participant">
        <div></div>
        <div class="label" style="color: black">Me</div>
      </div>
```
     Yes, I have the empty <div> this is my code

**Comment by sekeyrw** [comment]
![image](https://user-images.githubusercontent.com/71113187/205299084-82ff6411-58f0-4388-9bb3-d7eafdd7a286.png)

**Comment by miguelgrinberg** [comment]
Are you 100% positive that you have made no changes to the HTML file? The only explanation I can give you is that you have another element called `local` in the page that is being returned instead of the correct one.

**Comment by sekeyrw** [comment]
I am 100% sure that that ```div``` is the only id=local. I searched also my templates theres no id=local on the html files. I also tried to remove ```.firstChild;``` in the ```let video = document.getElementById('local').firstChild;``` and it starts running normally and no errors but the problem now is that the design are broken.

With ```.firstChild```: 
![image](https://user-images.githubusercontent.com/71113187/205319775-04a87991-21b4-414d-b38f-67a37b3f507e.png)

After I removed the ```.firstChild```:
![image](https://user-images.githubusercontent.com/71113187/205320064-a64b0632-815f-4a85-81fd-c13b931977f2.png)

**Comment by miguelgrinberg** [comment]
It's the spacing that you added that caused this. Note how I have the empty div in the same line as the parent, without any extra spacing around it.

I'll switch to `firstElementChild` to prevent this, seems like a better choice.

**Comment by sekeyrw** [comment]
> It's the spacing that you added that caused this. Note how I have the empty div in the same line as the parent, without any extra spacing around it.
> 
> I'll switch to `firstElementChild` to prevent this, seems like a better choice.

The spacing was caused by the extension Prettier. so i should disable my prettier?
