### ISSUE TITLE
Problem using the flask-twilio-video!!

### ISSUE THREAD

**Issue by 4TT4** [miguelgrinberg/flask-twilio-video#3]
![2](https://user-images.githubusercontent.com/60099972/86536405-de629b00-bf04-11ea-9b70-7911c9dc7b1a.JPG)
![1](https://user-images.githubusercontent.com/60099972/86536408-e0c4f500-bf04-11ea-8806-dcbe887e2b9a.JPG)

HI buddy , i am directly using your flask-twilio-video github repository .
i filled out .env template also , and i think am probably doing almost everything right , but still it is showing that error(refer the attachment/pics). Pls HELP!

**Comment by 4TT4** [comment]
![1](https://user-images.githubusercontent.com/60099972/86536439-40230500-bf05-11ea-9ced-75a1f39278b7.JPG)

**Comment by miguelgrinberg** [comment]
The `.env.template` is a just that, a template. The real file should be named `.env`.

**Comment by amchen82** [comment]
hi, Miguel, seems that route login takes the user name for the account specified in .env. 
How can i specify 'Name' ? No matter what i put in 'Name' in the local browser , it prompts'connection failed, is backend running?' . could you help ?

thanks a lot !

**Comment by BhargaviChintalapati** [comment]
I have issue when I tweak the code to take input from user for room name. I have updated my api to get the json variable for roon and updated js file with room variable as well in connect and other functions. But it throws error while connecting to meeting room


app.js
function connect(username, room) {
    let promise = new Promise((resolve, reject) => {
        // get a token from the back end
        fetch('/login', {
            method: 'POST',
            body: JSON.stringify({'username': username, 'room': room})
        }).then(res => res.json()).then(data => {
            // join video call
            return Twilio.Video.connect(data.token);
        }).then(_room => {
            room = _room;
            room.participants.forEach(participantConnected);
            room.on(`participantConnected`, participantConnected);
            room.on('participantDisconnected', participantDisconnected);
            connected = true;
            updateParticipantCount();
            resolve();
        }).catch(() => {
            //reject();
            alert('error in connect');
        });
    });
    return promise;
};

app.py

@app.route('/login', methods=['POST'])
def login():
    username = request.get_json(force=True).get('username')
    room = request.get_json(force=True).get('room')
    print(username)
    print(room)
    if not username:
        abort(401)

    token = AccessToken(twilio_account_sid, twilio_api_key_sid,
                        twilio_api_key_secret)
    token.identity = username
    grant = VideoGrant()
    grant.room = room
    token.add_grant(grant)
    #token.add_grant(VideoGrant(room=room))

    return {'token': token.to_jwt().decode()}

**Comment by miguelgrinberg** [comment]
What's the error?

**Comment by BhargaviChintalapati** [comment]
I get the alert('Connection failed. Is the backend running?'); as per js file. Once I click okay, I could see the video tiles joined by users but the button still shows "Join Call", both Join call and screen share buttons are disabled

**Comment by miguelgrinberg** [comment]
@BhargaviChintalapati This must be a logic problem in the changes that you've made to the application. I can't really help you with that, use your debugger to find why the button isn't being updated to its new state.
