### ISSUE TITLE
phone can't get camera

### ISSUE THREAD

**Issue by amchen82** [miguelgrinberg/flask-twilio-video#5]
Hi, Miguel, 

I am able to connect to local server and join the call in my local computer
After getting a https url setup through ngrok, im able to connect and see index.html on phone. But when enter name to join call, printer page comes out. The same thing happens when i use a different computer. 
Would you please suggest anything i should check ?
Thanks a lot !

**Comment by miguelgrinberg** [comment]
Printer page? What do you mean? The same as selecting the Print option?

Also, check the browser's console and network tabs for errors.

**Comment by amchen82** [comment]
thanks for reply ! 
On the browser console, there was error saying device not found. So when i switch to another computer with camera it works. 
Android phone works too. but Iphone doesn't work. The problem is probably it can't get access to camera/speaker .....

**Comment by miguelgrinberg** [comment]
@amchen82 Are you using a supported web browser on the device you are having problems?

**Comment by arshit26** [comment]
I am facing this error too! It worked fine on Chrome/Android Phone, but isn't working on Chrome/iPhone. It's throwing "**_Connection failed. Is the backend running?"_** error

**Comment by amchen82** [comment]
if i use safari, it is able to access camera. but after join, the pic is black. Chrome isn't able to access camera at all. 
thanks for the reply again !

**Comment by miguelgrinberg** [comment]
@amchen82 That's why I asked if you were using the [supported browsers](https://www.twilio.com/docs/voice/client/javascript#supported-browsers). On iOS Chrome isn't supported, so no point in trying it. Safari is supported, so for that one you may want to talk to our support people to see if they can help you

**Comment by gowrath** [comment]
I have the same issue--I'm using supported browsers. The other person can see me, but they don't see themselves. It works fine on my local machine—I see myself and others. 

Where can I talk to support people?

**Comment by miguelgrinberg** [comment]
@gowrath https://www.twilio.com/console/support/tickets/create

**Comment by suffa07** [comment]
@gowrath Did you ever resolve your issue?

**Comment by gowrath** [comment]
I spoke to the team at Twilio. They recommended I build it in React: https://www.twilio.com/blog/build-a-chat-app-with-twilio-programmable-chat-and-react
