### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by techrishi** [miguelgrinberg/flask-twilio-video#7]
On running it is showing connection failed.is the backend working?

**Comment by miguelgrinberg** [comment]
The backend works, sure. Are you running it? Look in the network tab of your browser to see more details.

**Comment by techrishi** [comment]
Actually I meant on clicking the join call tab, it displays the message"connection failed.is the back end working?"

**Comment by sr347012** [comment]
I am getting the same error too. How do you run the back end ? Is it by the command ' flask run' right ? I mean when you mention the flask run command, it runs the app.py file. Please correct me if I am wrong. Even I am trying to run this application. Just got stuck here.

**Comment by miguelgrinberg** [comment]
@sr347012 As I asked the OP, please look in the network tab of your browser for errors. Something is obviously happening on your side, but I need some help in debugging this, since I can run the application just fine here.

**Comment by techns27** [comment]
Hello @sr347012 @techrishi 
Please make sure you have renamed .env.template to .env and also you have define twilio api keys.
It seems, you forget that bit.

**Comment by techrishi** [comment]
I m getting this error

**Comment by miguelgrinberg** [comment]
I recorded a short video in which I go through all the steps in installing and running this application: https://www.youtube.com/watch?v=5hdrW6yEwro.

Hope this helps clarify the process.
