### ISSUE TITLE
I recorded a short video in which I go through all the steps in installing and running this application: https://www.youtube.com/watch?v=5hdrW6yEwro.

### ISSUE THREAD

**Issue by Devorasolomon** [miguelgrinberg/flask-twilio-video#8]
I recorded a short video in which I go through all the steps in installing and running this application: https://www.youtube.com/watch?v=5hdrW6yEwro.

Hope this helps clarify the process.

_Originally posted by @miguelgrinberg in https://github.com/miguelgrinberg/flask-twilio-video/issues/7#issuecomment-694259908_

**Comment by Devorasolomon** [comment]
Hi thanks for the video it is great, i still get the error when clicking on 'join video' Connection failed. Is the backend running?
in the network tab i do see a token what can this be?

**Comment by miguelgrinberg** [comment]
@Devorasolomon the problem is likely with your credentials, but if you think the issue is more complex than that please contact Twilio support for help.

**Comment by Devorasolomon** [comment]
> @Devorasolomon the problem is likely with your credentials, but if you think the issue is more complex than that please contact Twilio support for help.

Thanks! this was because i did not have a camera connected. thanks for your help
